apiVersion: apps/v1
kind: Deployment
metadata:
  name: musician
  labels:
    app: musician
spec:
  replicas: 3
  selector:
    matchLabels:
      app: musician
  template:
    metadata:
      labels:
        app: musician
    spec:
      containers:
      - name: musician
        image: hernansaltiveri/musician
        ports:
        - containerPort: 3001