apiVersion: v1
kind: Service
metadata:
  name: musician
  labels:
    run: musician
spec:
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: musician
  selector:
    app: musician
    run: musician
  type: LoadBalancer